spring.application.name=fdcTest
# Oracle DB 연결
spring.datasource.url=jdbc:oracle:thin:@heeDev:1521:XE
#spring.datasource.username=skfdc4
spring.datasource.username=fdc2
spring.datasource.password=s1111
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# MyBatis 설정
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=com.example.demo.dto

#쿼리 로그 찍기
mybatis.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl

# 에러로그 Write
# 로그 파일이 저장될 디렉토리 경로와 파일 이름 지정
logging.file.name=/logs/hynix-fdc/fdc-api.log

# 로그 레벨 설정 (INFO 레벨 이상만 기록, 에러는 당연히 포함)
logging.level.root=INFO

# 날짜별/용량별 파일 쪼개기 규칙 (스프링 부트 기본 로깅 시스템인 Logback 기능)
logging.logback.rollingpolicy.file-name-pattern=logs/hynix-fdc/fdc-api-%d{yyyy-MM-dd}.%i.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30
